site_name: Foundations of Programming Docs
nav:
    - Home: index.md
    - Chapters:
          - Chapter 1 - Setup: chapter-1-setup.md
          - Chapter 2 - Variables & Functions: chapter-2-variables-functions.md
          - Chapter 3 - Conditionals: chapter-3-conditionals.md
          - Chapter 4 - Git & Github: chapter-4-git-github.md
          - Chapter 5 - Loops: chapter-5-loops.md

theme:
    name: material
    features:
        - content.code.copy
        - header.autohide
        - search.suggest
        - navigation.path
        - navigation.top
        - toc.integrate
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - navigation.expand
    font:
        code: Roboto Mono
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to system preference
    plugins:
        - optimize
        - offline
        - search:
              indexing: "sections"
markdown_extensions:
    - admonition
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - extra
    - codehilite
    - wikilinks
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          auto_title: true
          linenums: true
          pygments_lang_class: true
          line_spans: __span
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.superfences
    - pymdownx.inlinehilite

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
    - css/style.css
